apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres # Sets the service name
  namespace: default
  labels:
    app: postgres # Defines app to create service for
spec:
  type:  NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30000
  selector:
    app: postgres
